site_name: MRI on BEAR
site_url: https://chbh-opensource.github.io/mri-on-bear-edu

repo_name: MRI-on-BEAR
repo_url: https://github.com/chbh-opensource/mri-on-bear-edu
edit_uri: blob/main/docs

theme:
  palette:
    primary: red
    accent: pink
  font:
    text: SF Pro Display
    code: SF Mono
  name: material
  custom_dir: overrides
  logo: assets/images/chbh_logo.jpg
  favicon: assets/images/chbh_logo.jpg
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chbh-on-bear
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-twitter-handle
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/your-gitlab-handle

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - toc:
      permalink: true
 
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started:
    - Accessing BlueBEAR and the BEAR Portal: setting-up.md
  - Workshop 1 - Introduction to BlueBEAR and Linux:
    - Workshop 1 - Aims and objectives: workshop1/workshop1-intro.md
    - Introduction to the BlueBEAR Portal: workshop1/intro-to-bluebear.md
    - Introduction to Linux: workshop1/intro-to-linux.md
  - Workshop 2 - Basic MRI skills:
    - Workshop 2 - Aims and objectives: workshop2/workshop2-intro.md
    - Working with MRI Data - Files and Formats: workshop2/mri-data-formats.md
    - MRI data visualization with FSLeyes: workshop2/visualizing-mri-data.md
  - Workshop 3 - Basic diffusion MRI analysis:
    - FSL's diffusion toolbox: workshop3/fsl-diffusion-toolbox.md
    - Diffusion tensor fitting: workshop3/diffusion-tensor-fitting.md
    - Tract-based spatial statistics (TBSS): workshop3/tbss.md
  - Workshop 4 - Advanced diffusion MRI analysis:
    - Probabilistic tractography: workshop4/probabilistic-tractography.md
    - Brain extraction: workshop4/brain-extraction.md
  - Workshop 5 - First-level fMRI analysis:
    - Manual and automatic brain extraction: workshop5/brain-extraction.md
    - Preprocessing of functional MRI data: workshop5/preprocessing-fmri.md
    - Running a first-level analysis: workshop5/first-level-analysis.md
  - Workshop 6 - Higher-level fMRI analysis:
    - Setting up and running a higher-level analysis using the FSL GUI: workshop6/higher-level-analysis.md
  - Workshop 7 - Bash scripting and region-of-interest analysis:
    - Scripting FSL commands: workshop7/scripting-fsl.md
    - Extracting statistics from region of interests: workshop7/extracting-statistics.md
  - Workshop 8 - Functional connectivity:
    - Functional connectivity analysis of resting-state fMRI data using FSL: workshop8/functional-connectivity.md
  - Additional Resources: resources.md
  - Contributors:
    - Contributing to the website: contributing/contributing.md